-- FULL SAFE SCHEMA: skip anything that already exists

DO $$ BEGIN CREATE TYPE public.user_role AS ENUM ('CUSTOMER', 'SHOP_OWNER', 'ADMIN'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.license_status AS ENUM ('PENDING', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.product_status AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING_REVIEW', 'RESTRICTED', 'BLOCKED', 'OUT_OF_STOCK'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.order_status AS ENUM ('PLACED', 'ACCEPTED', 'PREPARING', 'READY_FOR_PICKUP', 'CANCELLED', 'COMPLETED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.payment_status AS ENUM ('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE TABLE IF NOT EXISTS public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'CUSTOMER', full_name text, phone text, email text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.shops (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, name text not null, description text, logo_url text, phone text, email text, address text, city text, state text, postal_code text, is_open boolean not null default false, opening_hours jsonb not null default '{}'::jsonb, delivery_radius text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.shop_licenses (id uuid primary key default gen_random_uuid(), shop_id uuid not null references public.shops(id) on delete cascade, license_number text not null, status public.license_status not null default 'PENDING', approval_status text not null default 'PENDING', issued_at date, expires_at date, jurisdiction text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, image_url text, created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.products (id uuid primary key default gen_random_uuid(), shop_id uuid not null references public.shops(id) on delete cascade, category_id uuid references public.categories(id) on delete set null, name text not null, brand text, description text, size text, alcohol_percentage numeric(5,2) check (alcohol_percentage >= 0), price numeric(12,2) not null check (price >= 0), discount_price numeric(12,2) check (discount_price is null or discount_price >= 0), image_url text, status public.product_status not null default 'PENDING_REVIEW', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.inventory (id uuid primary key default gen_random_uuid(), product_id uuid not null unique references public.products(id) on delete cascade, stock integer not null default 0 check (stock >= 0), low_stock_threshold integer not null default 0 check (low_stock_threshold >= 0), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.addresses (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete cascade, label text not null, line text not null, city text not null, state text, postal_code text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.carts (id uuid primary key default gen_random_uuid(), customer_id uuid not null unique references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references public.carts(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, quantity integer not null check (quantity > 0), unique (cart_id, product_id));
CREATE TABLE IF NOT EXISTS public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique default ('DRK-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))), customer_id uuid not null references public.profiles(id) on delete restrict, shop_id uuid not null references public.shops(id) on delete restrict, address_id uuid references public.addresses(id) on delete set null, subtotal numeric(12,2) not null check (subtotal >= 0), delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0), discount numeric(12,2) not null default 0 check (discount >= 0), total numeric(12,2) not null check (total >= 0), currency text not null default 'INR', status public.order_status not null default 'PLACED', payment_status public.payment_status not null default 'PENDING', compliance_status text not null default 'PENDING', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name_snapshot text not null, price_snapshot numeric(12,2) not null check (price_snapshot >= 0), quantity integer not null check (quantity > 0), subtotal numeric(12,2) not null check (subtotal >= 0));
CREATE TABLE IF NOT EXISTS public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade, provider text, provider_payment_id text, amount numeric(12,2) not null check (amount >= 0), currency text not null default 'INR', status public.payment_status not null default 'PENDING', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.payment_events (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id) on delete cascade, event_type text not null, provider_event_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.offers (id uuid primary key default gen_random_uuid(), shop_id uuid not null references public.shops(id) on delete cascade, product_id uuid references public.products(id) on delete cascade, name text not null, offer_type text not null check (offer_type in ('PERCENTAGE', 'FIXED_AMOUNT')), value numeric(12,2) not null check (value >= 0), minimum_order numeric(12,2) not null default 0 check (minimum_order >= 0), maximum_discount numeric(12,2) check (maximum_discount is null or maximum_discount >= 0), starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'ACTIVE', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, shop_id uuid references public.shops(id) on delete cascade, title text not null, message text not null, read_at timestamptz, created_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.compliance_rules (id uuid primary key default gen_random_uuid(), jurisdiction text not null, customer_eligibility jsonb not null default '{}'::jsonb, product_restrictions jsonb not null default '{}'::jsonb, operating_hours jsonb not null default '{}'::jsonb, restricted_locations jsonb not null default '[]'::jsonb, order_restrictions jsonb not null default '{}'::jsonb, is_demo boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
CREATE TABLE IF NOT EXISTS public.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, status public.order_status not null, changed_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
DO $$ BEGIN CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TRIGGER shops_updated_at BEFORE UPDATE ON public.shops FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TRIGGER products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TRIGGER inventory_updated_at BEFORE UPDATE ON public.inventory FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN INSERT INTO public.profiles (id, full_name, phone, email, role) VALUES (new.id, new.raw_user_meta_data ->> 'full_name', new.phone, new.email, COALESCE((new.raw_user_meta_data ->> 'role')::public.user_role, 'CUSTOMER')) ON CONFLICT (id) DO NOTHING; RETURN new; END; $$;
DO $$ BEGIN CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user(); EXCEPTION WHEN duplicate_object THEN null; END $$;

CREATE OR REPLACE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'ADMIN'); $$;
CREATE OR REPLACE FUNCTION public.is_shop_owner() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'SHOP_OWNER'); $$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN DROP POLICY IF EXISTS profiles_select_own ON public.profiles; CREATE POLICY profiles_select_own ON public.profiles FOR SELECT USING (id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS profiles_insert_own ON public.profiles; CREATE POLICY profiles_insert_own ON public.profiles FOR INSERT WITH CHECK ((id = auth.uid() AND role = 'CUSTOMER') OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS profiles_update_own ON public.profiles; CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING (id = auth.uid() OR public.is_admin()) WITH CHECK (id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shops_read_public ON public.shops; CREATE POLICY shops_read_public ON public.shops FOR SELECT USING (owner_id = auth.uid() OR public.is_admin() OR NOT public.is_shop_owner()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shops_owner_insert ON public.shops; CREATE POLICY shops_owner_insert ON public.shops FOR INSERT WITH CHECK (owner_id = auth.uid() AND public.is_shop_owner()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shops_owner_update ON public.shops; CREATE POLICY shops_owner_update ON public.shops FOR UPDATE USING (owner_id = auth.uid() OR public.is_admin()) WITH CHECK (owner_id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shops_owner_delete ON public.shops; CREATE POLICY shops_owner_delete ON public.shops FOR DELETE USING (owner_id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS categories_read_public ON public.categories; CREATE POLICY categories_read_public ON public.categories FOR SELECT USING (true); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS products_read_public ON public.products; CREATE POLICY products_read_public ON public.products FOR SELECT USING ((status = 'ACTIVE' AND NOT public.is_shop_owner()) OR EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND s.owner_id = auth.uid()) OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS products_owner_write ON public.products; CREATE POLICY products_owner_write ON public.products FOR ALL USING (EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND (s.owner_id = auth.uid() OR public.is_admin()))) WITH CHECK (EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND (s.owner_id = auth.uid() OR public.is_admin()))); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS inventory_read_public ON public.inventory; CREATE POLICY inventory_read_public ON public.inventory FOR SELECT USING (EXISTS (SELECT 1 FROM public.products p WHERE p.id = product_id AND (p.status = 'ACTIVE' OR EXISTS (SELECT 1 FROM public.shops s WHERE s.id = p.shop_id AND s.owner_id = auth.uid()) OR public.is_admin()))); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS inventory_owner_write ON public.inventory; CREATE POLICY inventory_owner_write ON public.inventory FOR ALL USING (EXISTS (SELECT 1 FROM public.products p JOIN public.shops s ON s.id = p.shop_id WHERE p.id = product_id AND (s.owner_id = auth.uid() OR public.is_admin()))) WITH CHECK (EXISTS (SELECT 1 FROM public.products p JOIN public.shops s ON s.id = p.shop_id WHERE p.id = product_id AND (s.owner_id = auth.uid() OR public.is_admin()))); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS addresses_own ON public.addresses; CREATE POLICY addresses_own ON public.addresses FOR ALL USING (customer_id = auth.uid() OR public.is_admin()) WITH CHECK (customer_id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS carts_own ON public.carts; CREATE POLICY carts_own ON public.carts FOR ALL USING (customer_id = auth.uid() OR public.is_admin()) WITH CHECK (customer_id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS cart_items_own ON public.cart_items; CREATE POLICY cart_items_own ON public.cart_items FOR ALL USING (EXISTS (SELECT 1 FROM public.carts c WHERE c.id = cart_id AND c.customer_id = auth.uid()) OR public.is_admin()) WITH CHECK (EXISTS (SELECT 1 FROM public.carts c WHERE c.id = cart_id AND c.customer_id = auth.uid()) OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS orders_customer_or_shop ON public.orders; CREATE POLICY orders_customer_or_shop ON public.orders FOR SELECT USING (customer_id = auth.uid() OR EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND s.owner_id = auth.uid()) OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS orders_customer_insert ON public.orders; CREATE POLICY orders_customer_insert ON public.orders FOR INSERT WITH CHECK (customer_id = auth.uid()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS offers_read_public ON public.offers; CREATE POLICY offers_read_public ON public.offers FOR SELECT USING (EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND s.owner_id = auth.uid()) OR public.is_admin() OR NOT public.is_shop_owner()); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS offers_owner_write ON public.offers; CREATE POLICY offers_owner_write ON public.offers FOR ALL USING (EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND (s.owner_id = auth.uid() OR public.is_admin()))) WITH CHECK (EXISTS (SELECT 1 FROM public.shops s WHERE s.id = shop_id AND (s.owner_id = auth.uid() OR public.is_admin()))); EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS notifications_own ON public.notifications; CREATE POLICY notifications_own ON public.notifications FOR ALL USING (user_id = auth.uid() OR public.is_admin()) WITH CHECK (user_id = auth.uid() OR public.is_admin()); EXCEPTION WHEN undefined_object THEN null; END $$;

INSERT INTO public.categories (name, slug, image_url) VALUES ('Beer', 'beer', null), ('Whisky', 'whisky', null), ('Vodka', 'vodka', null), ('Rum', 'rum', null), ('Wine', 'wine', null) ON CONFLICT (slug) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('shop-images', 'shop-images', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('profile-images', 'profile-images', false) ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN DROP POLICY IF EXISTS product_images_read ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS product_images_manage ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS product_images_insert ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS product_images_write ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shop_images_read ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;
DO $$ BEGIN DROP POLICY IF EXISTS shop_images_manage ON storage.objects; EXCEPTION WHEN undefined_object THEN null; END $$;

CREATE POLICY product_images_read ON storage.objects FOR SELECT USING (bucket_id = 'product-images' AND auth.uid() IS NOT NULL);
CREATE POLICY product_images_write ON storage.objects FOR ALL USING (bucket_id = 'product-images' AND auth.uid() IS NOT NULL) WITH CHECK (bucket_id = 'product-images' AND auth.uid() IS NOT NULL);
CREATE POLICY shop_images_read ON storage.objects FOR SELECT USING (bucket_id = 'shop-images' AND auth.uid() IS NOT NULL);
CREATE POLICY shop_images_manage ON storage.objects FOR ALL USING (bucket_id = 'shop-images' AND auth.uid() IS NOT NULL) WITH CHECK (bucket_id = 'shop-images' AND auth.uid() IS NOT NULL);
